export const primary = 'cadetblue'
export const secondary = 'royalblue'
export const success = 'limegreen'
export const danger = 'indianred'
export const white = 'white'
export const background = '#1D2330'
